server:
  port: 8081
  shutdown: graceful
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: ${MONGO_URI}
  cloud:
    aws:
      credentials:
        access-key: ${SQS_ACCESS}
        secret-key: ${SQS_SECRET}
      region:
        static: ap-northeast-2
