server:
  port: 8081
  shutdown: graceful
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
     uri: mongodb://localhost:27017/squirrel_db
     auto-index-creation: true
